CREATE TABLE transferred_students (
	student_id BIGINT NOT NULL,
	institute_id BIGINT NOT NULL,
	from_program_id bigint NOT NULL,
  	from_department_id bigint NOT NULL,
	from_level_id  bigint NOT NULL default 0,
	from_level_section_id bigint NOT NULL default 0,
	transferred_program_id bigint NOT NULL,
  	transferred_department_id bigint NOT NULL,
	transferred_level_id  bigint NOT NULL default 0,
	transferred_level_section_id bigint NOT NULL default 0,
	transfer_done_by BIGINT NOT NULL,
	season_id BIGINT NOT NULL,
	created_at timestamp
);

CREATE TABLE unregistered_subjects (
	subject_register_id BIGSERIAL PRIMARY KEY,
  institute_id bigint NOT NULL,
  subject_id bigint NOT NULL,
  section_id bigint NOT NULL,
  student_id bigint NOT NULL,
  season_id bigint NOT NULL,
  offered_subject_id bigint NOT NULL,
  subject_section_id bigint NOT NULL,
  total_classes int  default 0 NOT NULL,
  total_attendance int  default 0 NOT NULL,
  overall_attendance character varying NOT NULL default '',
  has_attendance_shortage boolean NOT NULL default true,
  is_condonable boolean NOT NULL default false, 
  attendance_entered_by bigint NOT NULL default 0,
  is_condoned boolean NOT NULL default FALSE,
  condoned_by_user bigint NOT NULL default 0,
  cie_marks integer NOT NULL default 0,
  has_cie_shortage boolean NOT NULL default true,
  is_eligible_for_exam boolean NOT NULL default FALSE,
  has_attended_exam boolean not null default false,
  is_eligible_for_makeup boolean not null default false,
  has_opted_for_makeup boolean NOT NULL default FALSE,
  has_attended_makeup boolean not null default false,
  is_eligible_to_withdraw boolean NOT NULL default true,
  has_withdrawn boolean NOT NULL default false,
  is_authorized_absence boolean NOT NULL default false,
  exam_marks int not null default 0,
  grade character varying not null default '',
  created_at timestamp,
  updated_at timestamp,
  UNIQUE(subject_register_id, student_id, season_id)
);